# Build options
SKETCH :=   GameCard
BOARD :=    arduino:avr:uno
PORT :=     /dev/ttyACM0
ASC :=      arduino

# Autogenerated stuff
HPPFILES := $(wildcard $(SKETCH)/*.hpp)
CPPFILES := $(wildcard $(SKETCH)/*.cpp)

# Helper targets
.PHONY : all
all : upload

.PHONY : verify
verify : $(SKETCH)/$(SKETCH).ino $(HPPFILES) $(CPPFILES)
	$(ASC) --verify --board $(BOARD) $<

.PHONY : upload
upload : $(SKETCH)/$(SKETCH).ino $(HPPFILES) $(CPPFILES)
	$(ASC) --upload --board $(BOARD) $<

.PHONY : list
list :
	@$(MAKE) -pRrq -f $(lastword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$'
